name: DailyTrack Cron Job

on:
  schedule:
    # Runs at 18:30 UTC every day (which is exactly 12:00 AM Midnight IST)
    - cron: '* * * * *'
  workflow_dispatch: # Allows you to run it manually from the GitHub UI

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend Cron Route
        env:
          API_KEY: ${{ secrets.DT_API_KEY }}
        run: |
          curl -X POST https://sabarishhh14-dailytrack-v2.hf.space/api/cron/process-recurring \
               -H "X-API-KEY: ${API_KEY}"